[project]
name = "plm-interact"
version = "0.1.0"
description = "PLM-interact: extending protein language models to predict protein-protein interactions"
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"]

[tasks]
default = "python --version"

[dependencies]
python = "3.10.*"
pip = "*"
cuda = "11.8.*"
pytorch = { version = ">=2.0", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }

[pypi-dependencies]
transformers = "==4.40.1"
sentence-transformers = "*"
datasets = "*"
scipy = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"
biopython = "*"
seaborn = "*"
scikit-learn = "*"
huggingface_hub = "*"
click = "*"
tqdm = "*"
mosaicml-streaming = "*"
